import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CLT test project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mx-auto my-auto block py-8 text-center">
          <h2 className="text-2xl font-bold">CLT test project</h2>
        </header>
        <div className="">
          <nav className="navbar navbar-expand-lg bg-body-tertiary">
            <div className="container-fluid">
              <a className="navbar-brand" href="#">
                Home
              </a>

              <ul className="nav">
                <li className="nav-item">
                  <a className="nav-link" href="/employees">
                    Employees
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/schedules/report">
                    Schedules Report
                  </a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
        <aside className="w-auto">{children}</aside>
      </body>
    </html>
  );
}
